/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCommentsRouteImport } from './routes/_authenticated/comments'
import { Route as AuthenticatedPublishedRouteImport } from './routes/_authenticated/published'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as MapsSlugRouteImport } from './routes/maps.$slug'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdCommentsRouteImport } from './routes/_authenticated/projects.$projectId.comments'
import { Route as AuthenticatedProjectsProjectIdDetailsRouteImport } from './routes/_authenticated/projects.$projectId.details'
import { Route as AuthenticatedProjectsProjectIdMapRouteImport } from './routes/_authenticated/projects.$projectId.map'
import { Route as AuthenticatedProjectsProjectIdPublishRouteImport } from './routes/_authenticated/projects.$projectId.publish'
import { Route as AuthenticatedProjectsProjectIdPublishingRouteImport } from './routes/_authenticated/projects.$projectId.publishing'
import { Route as AuthenticatedProjectsProjectIdStylingRouteImport } from './routes/_authenticated/projects.$projectId.styling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommentsRoute = AuthenticatedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedRoute = AuthenticatedPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MapsSlugRoute = MapsSlugRouteImport.update({
  id: '/maps/$slug',
  path: '/maps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdCommentsRoute =
  AuthenticatedProjectsProjectIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDetailsRoute =
  AuthenticatedProjectsProjectIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMapRoute =
  AuthenticatedProjectsProjectIdMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPublishRoute =
  AuthenticatedProjectsProjectIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPublishingRoute =
  AuthenticatedProjectsProjectIdPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdStylingRoute =
  AuthenticatedProjectsProjectIdStylingRouteImport.update({
    id: '/styling',
    path: '/styling',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/maps/$slug': typeof MapsSlugRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/comments': typeof AuthenticatedProjectsProjectIdCommentsRoute
  '/projects/$projectId/details': typeof AuthenticatedProjectsProjectIdDetailsRoute
  '/projects/$projectId/map': typeof AuthenticatedProjectsProjectIdMapRoute
  '/projects/$projectId/publish': typeof AuthenticatedProjectsProjectIdPublishRoute
  '/projects/$projectId/publishing': typeof AuthenticatedProjectsProjectIdPublishingRoute
  '/projects/$projectId/styling': typeof AuthenticatedProjectsProjectIdStylingRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/maps/$slug': typeof MapsSlugRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/comments': typeof AuthenticatedProjectsProjectIdCommentsRoute
  '/projects/$projectId/details': typeof AuthenticatedProjectsProjectIdDetailsRoute
  '/projects/$projectId/map': typeof AuthenticatedProjectsProjectIdMapRoute
  '/projects/$projectId/publish': typeof AuthenticatedProjectsProjectIdPublishRoute
  '/projects/$projectId/publishing': typeof AuthenticatedProjectsProjectIdPublishingRoute
  '/projects/$projectId/styling': typeof AuthenticatedProjectsProjectIdStylingRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/published': typeof AuthenticatedPublishedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/maps/$slug': typeof MapsSlugRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/comments': typeof AuthenticatedProjectsProjectIdCommentsRoute
  '/_authenticated/projects/$projectId/details': typeof AuthenticatedProjectsProjectIdDetailsRoute
  '/_authenticated/projects/$projectId/map': typeof AuthenticatedProjectsProjectIdMapRoute
  '/_authenticated/projects/$projectId/publish': typeof AuthenticatedProjectsProjectIdPublishRoute
  '/_authenticated/projects/$projectId/publishing': typeof AuthenticatedProjectsProjectIdPublishingRoute
  '/_authenticated/projects/$projectId/styling': typeof AuthenticatedProjectsProjectIdStylingRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comments'
    | '/published'
    | '/settings'
    | '/maps/$slug'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/comments'
    | '/projects/$projectId/details'
    | '/projects/$projectId/map'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/publishing'
    | '/projects/$projectId/styling'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comments'
    | '/published'
    | '/settings'
    | '/maps/$slug'
    | '/projects'
    | '/projects/$projectId/comments'
    | '/projects/$projectId/details'
    | '/projects/$projectId/map'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/publishing'
    | '/projects/$projectId/styling'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/comments'
    | '/_authenticated/published'
    | '/_authenticated/settings'
    | '/maps/$slug'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/comments'
    | '/_authenticated/projects/$projectId/details'
    | '/_authenticated/projects/$projectId/map'
    | '/_authenticated/projects/$projectId/publish'
    | '/_authenticated/projects/$projectId/publishing'
    | '/_authenticated/projects/$projectId/styling'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MapsSlugRoute: typeof MapsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published': {
      id: '/_authenticated/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof AuthenticatedPublishedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/maps/$slug': {
      id: '/maps/$slug'
      path: '/maps/$slug'
      fullPath: '/maps/$slug'
      preLoaderRoute: typeof MapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/comments': {
      id: '/_authenticated/projects/$projectId/comments'
      path: '/comments'
      fullPath: '/projects/$projectId/comments'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCommentsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/details': {
      id: '/_authenticated/projects/$projectId/details'
      path: '/details'
      fullPath: '/projects/$projectId/details'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDetailsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/map': {
      id: '/_authenticated/projects/$projectId/map'
      path: '/map'
      fullPath: '/projects/$projectId/map'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMapRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/publish': {
      id: '/_authenticated/projects/$projectId/publish'
      path: '/publish'
      fullPath: '/projects/$projectId/publish'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPublishRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/publishing': {
      id: '/_authenticated/projects/$projectId/publishing'
      path: '/publishing'
      fullPath: '/projects/$projectId/publishing'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPublishingRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/styling': {
      id: '/_authenticated/projects/$projectId/styling'
      path: '/styling'
      fullPath: '/projects/$projectId/styling'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdStylingRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdCommentsRoute: typeof AuthenticatedProjectsProjectIdCommentsRoute
  AuthenticatedProjectsProjectIdDetailsRoute: typeof AuthenticatedProjectsProjectIdDetailsRoute
  AuthenticatedProjectsProjectIdMapRoute: typeof AuthenticatedProjectsProjectIdMapRoute
  AuthenticatedProjectsProjectIdPublishRoute: typeof AuthenticatedProjectsProjectIdPublishRoute
  AuthenticatedProjectsProjectIdPublishingRoute: typeof AuthenticatedProjectsProjectIdPublishingRoute
  AuthenticatedProjectsProjectIdStylingRoute: typeof AuthenticatedProjectsProjectIdStylingRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdCommentsRoute:
      AuthenticatedProjectsProjectIdCommentsRoute,
    AuthenticatedProjectsProjectIdDetailsRoute:
      AuthenticatedProjectsProjectIdDetailsRoute,
    AuthenticatedProjectsProjectIdMapRoute:
      AuthenticatedProjectsProjectIdMapRoute,
    AuthenticatedProjectsProjectIdPublishRoute:
      AuthenticatedProjectsProjectIdPublishRoute,
    AuthenticatedProjectsProjectIdPublishingRoute:
      AuthenticatedProjectsProjectIdPublishingRoute,
    AuthenticatedProjectsProjectIdStylingRoute:
      AuthenticatedProjectsProjectIdStylingRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedPublishedRoute: typeof AuthenticatedPublishedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedPublishedRoute: AuthenticatedPublishedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MapsSlugRoute: MapsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
