/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UsernameMapSlugRouteImport } from './routes/$username.$mapSlug'
import { Route as AuthenticatedCommentsRouteImport } from './routes/_authenticated/comments'
import { Route as AuthenticatedPublishedRouteImport } from './routes/_authenticated/published'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectSlugRouteImport } from './routes/_authenticated/projects.$projectSlug'
import { Route as AuthenticatedProjectsProjectSlugIndexRouteImport } from './routes/_authenticated/projects.$projectSlug.index'
import { Route as AuthenticatedProjectsProjectSlugCommentsRouteImport } from './routes/_authenticated/projects.$projectSlug.comments'
import { Route as AuthenticatedProjectsProjectSlugDetailsRouteImport } from './routes/_authenticated/projects.$projectSlug.details'
import { Route as AuthenticatedProjectsProjectSlugMapRouteImport } from './routes/_authenticated/projects.$projectSlug.map'
import { Route as AuthenticatedProjectsProjectSlugPublishRouteImport } from './routes/_authenticated/projects.$projectSlug.publish'
import { Route as AuthenticatedProjectsProjectSlugPublishingRouteImport } from './routes/_authenticated/projects.$projectSlug.publishing'
import { Route as AuthenticatedProjectsProjectSlugStylingRouteImport } from './routes/_authenticated/projects.$projectSlug.styling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameMapSlugRoute = UsernameMapSlugRouteImport.update({
  id: '/$username/$mapSlug',
  path: '/$username/$mapSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommentsRoute = AuthenticatedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedRoute = AuthenticatedPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectSlugRoute =
  AuthenticatedProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectSlugIndexRoute =
  AuthenticatedProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugCommentsRoute =
  AuthenticatedProjectsProjectSlugCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugDetailsRoute =
  AuthenticatedProjectsProjectSlugDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugMapRoute =
  AuthenticatedProjectsProjectSlugMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugPublishRoute =
  AuthenticatedProjectsProjectSlugPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugPublishingRoute =
  AuthenticatedProjectsProjectSlugPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)
const AuthenticatedProjectsProjectSlugStylingRoute =
  AuthenticatedProjectsProjectSlugStylingRouteImport.update({
    id: '/styling',
    path: '/styling',
    getParentRoute: () => AuthenticatedProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$username/$mapSlug': typeof UsernameMapSlugRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugRouteWithChildren
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectSlug/comments': typeof AuthenticatedProjectsProjectSlugCommentsRoute
  '/projects/$projectSlug/details': typeof AuthenticatedProjectsProjectSlugDetailsRoute
  '/projects/$projectSlug/map': typeof AuthenticatedProjectsProjectSlugMapRoute
  '/projects/$projectSlug/publish': typeof AuthenticatedProjectsProjectSlugPublishRoute
  '/projects/$projectSlug/publishing': typeof AuthenticatedProjectsProjectSlugPublishingRoute
  '/projects/$projectSlug/styling': typeof AuthenticatedProjectsProjectSlugStylingRoute
  '/projects/$projectSlug/': typeof AuthenticatedProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$username/$mapSlug': typeof UsernameMapSlugRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectSlug/comments': typeof AuthenticatedProjectsProjectSlugCommentsRoute
  '/projects/$projectSlug/details': typeof AuthenticatedProjectsProjectSlugDetailsRoute
  '/projects/$projectSlug/map': typeof AuthenticatedProjectsProjectSlugMapRoute
  '/projects/$projectSlug/publish': typeof AuthenticatedProjectsProjectSlugPublishRoute
  '/projects/$projectSlug/publishing': typeof AuthenticatedProjectsProjectSlugPublishingRoute
  '/projects/$projectSlug/styling': typeof AuthenticatedProjectsProjectSlugStylingRoute
  '/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$username/$mapSlug': typeof UsernameMapSlugRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/published': typeof AuthenticatedPublishedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/projects/$projectSlug': typeof AuthenticatedProjectsProjectSlugRouteWithChildren
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectSlug/comments': typeof AuthenticatedProjectsProjectSlugCommentsRoute
  '/_authenticated/projects/$projectSlug/details': typeof AuthenticatedProjectsProjectSlugDetailsRoute
  '/_authenticated/projects/$projectSlug/map': typeof AuthenticatedProjectsProjectSlugMapRoute
  '/_authenticated/projects/$projectSlug/publish': typeof AuthenticatedProjectsProjectSlugPublishRoute
  '/_authenticated/projects/$projectSlug/publishing': typeof AuthenticatedProjectsProjectSlugPublishingRoute
  '/_authenticated/projects/$projectSlug/styling': typeof AuthenticatedProjectsProjectSlugStylingRoute
  '/_authenticated/projects/$projectSlug/': typeof AuthenticatedProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/$username/$mapSlug'
    | '/comments'
    | '/published'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/'
    | '/projects/$projectSlug/comments'
    | '/projects/$projectSlug/details'
    | '/projects/$projectSlug/map'
    | '/projects/$projectSlug/publish'
    | '/projects/$projectSlug/publishing'
    | '/projects/$projectSlug/styling'
    | '/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/$username/$mapSlug'
    | '/comments'
    | '/published'
    | '/settings'
    | '/projects'
    | '/projects/$projectSlug/comments'
    | '/projects/$projectSlug/details'
    | '/projects/$projectSlug/map'
    | '/projects/$projectSlug/publish'
    | '/projects/$projectSlug/publishing'
    | '/projects/$projectSlug/styling'
    | '/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/$username/$mapSlug'
    | '/_authenticated/comments'
    | '/_authenticated/published'
    | '/_authenticated/settings'
    | '/_authenticated/projects/$projectSlug'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectSlug/comments'
    | '/_authenticated/projects/$projectSlug/details'
    | '/_authenticated/projects/$projectSlug/map'
    | '/_authenticated/projects/$projectSlug/publish'
    | '/_authenticated/projects/$projectSlug/publishing'
    | '/_authenticated/projects/$projectSlug/styling'
    | '/_authenticated/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsernameMapSlugRoute: typeof UsernameMapSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$mapSlug': {
      id: '/$username/$mapSlug'
      path: '/$username/$mapSlug'
      fullPath: '/$username/$mapSlug'
      preLoaderRoute: typeof UsernameMapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published': {
      id: '/_authenticated/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof AuthenticatedPublishedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectSlug': {
      id: '/_authenticated/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectSlug/': {
      id: '/_authenticated/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/comments': {
      id: '/_authenticated/projects/$projectSlug/comments'
      path: '/comments'
      fullPath: '/projects/$projectSlug/comments'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugCommentsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/details': {
      id: '/_authenticated/projects/$projectSlug/details'
      path: '/details'
      fullPath: '/projects/$projectSlug/details'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugDetailsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/map': {
      id: '/_authenticated/projects/$projectSlug/map'
      path: '/map'
      fullPath: '/projects/$projectSlug/map'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugMapRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/publish': {
      id: '/_authenticated/projects/$projectSlug/publish'
      path: '/publish'
      fullPath: '/projects/$projectSlug/publish'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugPublishRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/publishing': {
      id: '/_authenticated/projects/$projectSlug/publishing'
      path: '/publishing'
      fullPath: '/projects/$projectSlug/publishing'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugPublishingRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
    '/_authenticated/projects/$projectSlug/styling': {
      id: '/_authenticated/projects/$projectSlug/styling'
      path: '/styling'
      fullPath: '/projects/$projectSlug/styling'
      preLoaderRoute: typeof AuthenticatedProjectsProjectSlugStylingRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectSlugRoute
    }
  }
}

interface AuthenticatedProjectsProjectSlugRouteChildren {
  AuthenticatedProjectsProjectSlugCommentsRoute: typeof AuthenticatedProjectsProjectSlugCommentsRoute
  AuthenticatedProjectsProjectSlugDetailsRoute: typeof AuthenticatedProjectsProjectSlugDetailsRoute
  AuthenticatedProjectsProjectSlugMapRoute: typeof AuthenticatedProjectsProjectSlugMapRoute
  AuthenticatedProjectsProjectSlugPublishRoute: typeof AuthenticatedProjectsProjectSlugPublishRoute
  AuthenticatedProjectsProjectSlugPublishingRoute: typeof AuthenticatedProjectsProjectSlugPublishingRoute
  AuthenticatedProjectsProjectSlugStylingRoute: typeof AuthenticatedProjectsProjectSlugStylingRoute
  AuthenticatedProjectsProjectSlugIndexRoute: typeof AuthenticatedProjectsProjectSlugIndexRoute
}

const AuthenticatedProjectsProjectSlugRouteChildren: AuthenticatedProjectsProjectSlugRouteChildren =
  {
    AuthenticatedProjectsProjectSlugCommentsRoute:
      AuthenticatedProjectsProjectSlugCommentsRoute,
    AuthenticatedProjectsProjectSlugDetailsRoute:
      AuthenticatedProjectsProjectSlugDetailsRoute,
    AuthenticatedProjectsProjectSlugMapRoute:
      AuthenticatedProjectsProjectSlugMapRoute,
    AuthenticatedProjectsProjectSlugPublishRoute:
      AuthenticatedProjectsProjectSlugPublishRoute,
    AuthenticatedProjectsProjectSlugPublishingRoute:
      AuthenticatedProjectsProjectSlugPublishingRoute,
    AuthenticatedProjectsProjectSlugStylingRoute:
      AuthenticatedProjectsProjectSlugStylingRoute,
    AuthenticatedProjectsProjectSlugIndexRoute:
      AuthenticatedProjectsProjectSlugIndexRoute,
  }

const AuthenticatedProjectsProjectSlugRouteWithChildren =
  AuthenticatedProjectsProjectSlugRoute._addFileChildren(
    AuthenticatedProjectsProjectSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedPublishedRoute: typeof AuthenticatedPublishedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectSlugRoute: typeof AuthenticatedProjectsProjectSlugRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedPublishedRoute: AuthenticatedPublishedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectSlugRoute:
    AuthenticatedProjectsProjectSlugRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsernameMapSlugRoute: UsernameMapSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
